baseURL = "https://aiopentec.github.io/openalts/"
languageCode = "en-us"
title = "OpenAlts"
publishDir = "docs"

[taxonomies]
category = "categories"

[params]
description = "Open source alternatives to popular software tools."

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  lastmod = true


enableRobotsTXT = true
